# Generated by Django 4.2.4 on 2023-08-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_question_user_review_alter_coffee_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='coffee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.coffee'),
            preserve_default=False,
        ),
    ]
