# Generated by Django 4.2.4 on 2023-08-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
